### ISSUE TITLE
Checksummed address doesn't need to show up twice

### ISSUE THREAD

**Issue by treeder** [gochain-io/wallet#12]
Just once, at the top. 

<img width="716" alt="screen shot 2018-06-08 at 6 52 11 am" src="https://user-images.githubusercontent.com/75826/41154617-a72f3dd6-6ae8-11e8-94e1-4fd149a5b814.png">

**Comment by chovy** [comment]
@treeder  You want me to replace the non-checksummed address with the checksummed one?

**Comment by chovy** [comment]
@treeder it looks like someone removed the heading.
