### ISSUE TITLE
User issue deploying contract

### ISSUE THREAD

**Issue by treeder** [gochain-io/wallet#25]
t.me/gochain_testnet/4884

**Comment by r-kononov** [comment]
![image](https://user-images.githubusercontent.com/40002763/45927192-13307880-bf51-11e8-9bdf-eead773794e7.png)

![image](https://user-images.githubusercontent.com/40002763/45927197-217e9480-bf51-11e8-8b7c-78b868062c91.png)

A simple contract("helloworld") works perfectly, asked used for the details
