### ISSUE TITLE
Enable Custom Gas Limit for 'Use Contract'

### ISSUE THREAD

**Issue by jmank88** [gochain-io/wallet#41]
When deploying a contract, the user has the option of overriding the default gas limit of 300,000:
![screenshot from 2018-12-20 08-28-00](https://user-images.githubusercontent.com/1194128/50290412-34f6aa00-0431-11e9-9338-4a3f509c7b0c.png)
When using a contract, the user does not have that option, and the gas limit defaults to 2,000,000:
![screenshot from 2018-12-20 08-28-10](https://user-images.githubusercontent.com/1194128/50290415-36c06d80-0431-11e9-99e8-fe561aa04adf.png)
([example tx](https://explorer.gochain.io/tx/0x3664977ec764b3c3977bca5526825829617cfcb5bb282836f3e4509675018bfd))
Users should have the option to override just like when deploying.

An additional 'nice to have' feature would be to use `eth_estimateGas` either automatically or via a manual 'auto-fill' button to calculate an appropriate gas limit, so they don't have to guess.

**Comment by TeamDeedCoin** [comment]
It does seem to automatically use 2,000,000 by default for deploying for me. So I had success in launching a contract that uses less than 2mil.

![scrn1](https://user-images.githubusercontent.com/32532643/50295362-e7386c80-0445-11e9-985b-e5567572f34b.png)

Result:

![scrn2](https://user-images.githubusercontent.com/32532643/50295472-14851a80-0446-11e9-9744-927020a44a53.png)

**Comment by treeder** [comment]
Must be a big contract!  :)   fixing now.

**Comment by treeder** [comment]
PR is in: https://github.com/gochain-io/wallet/pull/43
