### ISSUE TITLE
Verification HTTP 400 Error

### ISSUE THREAD

**Issue by jmank88** [gochain-io/wallet#44]
Attempts to verify this contract result in error:
https://explorer.gochain.io/verify?address=0xA7620862540F635342B166206108D7B31C875Dd8
Name: MirrorSC
Code: https://gist.github.com/jmank88/c86d4bd7772ac90954320914f1d60ecc

The interface displays: `ERROR OCCURRED DURING ANTI-BOT CHECKING. PLEASE TRY AGAIN`

The javascript console shows `https://explorer.gochain.io/api/verify` returning `400` and then a null field access on the empty response object.

**Comment by treeder** [comment]
Should this be in explorer repo?

**Comment by jmank88** [comment]
https://github.com/gochain-io/explorer/issues/211
