### ISSUE TITLE
Append requisite 0x on private key entry from MEW format

### ISSUE THREAD

**Issue by cryptolarity** [gochain-io/wallet#7]
When generating an ETH private key from MEW it omits the '0x' and results in generating a different public address when inputting into the 'Send tx' portion of the GO wallet.

**Comment by jmank88** [comment]
This is likely as simple as checking for the `0x` prefix before trimming the first two chars. These screenshots demonstrate that *replacing* the first chars yields the same account, so it seems like those first two chars are being trimmed no matter what they are.
![screenshot from 2018-05-30 10-10-54](https://user-images.githubusercontent.com/1194128/40729343-c5c5bb74-63f1-11e8-97c2-e02e67f9d370.png)
![screenshot from 2018-05-30 10-11-01](https://user-images.githubusercontent.com/1194128/40729347-c7ff0bca-63f1-11e8-8df0-6274cc7ff247.png)
We should probably validate the length of the key too (are they fixed?), and the characters themselves. It accepts all sorts of random stuff, like just `0x12` for example:
![screenshot from 2018-05-30 10-14-06](https://user-images.githubusercontent.com/1194128/40729537-35948f0c-63f2-11e8-9ef1-8a2c284cc9a4.png)
Or random non-hex chars:
![screenshot from 2018-05-30 10-15-48](https://user-images.githubusercontent.com/1194128/40729655-72f1bde8-63f2-11e8-80aa-f1c7f927ce00.png)

**Comment by chovy** [comment]
What needs to be done on the UI here? Do I just search for `0x` and remove it? or do I add it if its not there?

**Comment by treeder** [comment]
We want to make sure:

* they have the 0x in front, and if not, either error or add it automatically (and update the actual form field)
* check that it's a valid key. Not sure if there's a method in web3 that verifies it?  More info here: https://ethereum.stackexchange.com/questions/1771/how-to-validate-a-private-key

**Comment by treeder** [comment]
Where is this one at?

**Comment by chovy** [comment]
I haven't started on this one yet.

**Comment by chovy** [comment]
I'm looking into this one now.
